{"uuid":"9e220a7e-5b74-4371-ac98-816a404956ab","historyId":"c8d778410ae6f0aaf37ea58fa2eb8019","status":"passed","statusDetails":null,"stage":"finished","steps":[{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138837117,"name":"visit / -> 302: https://opensource-demo.orangehrmlive.com/web/index.php/auth/login","stop":1692138849131},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138849128,"name":"GET --- /web/index.php/core/i18n/messages","stop":1692138849129},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138849132,"name":"fixture (\"example\")","stop":1692138849173},{"status":"passed","statusDetails":{},"stage":"finished","steps":[{"status":"passed","statusDetails":{},"stage":"finished","steps":[{"status":"passed","statusDetails":{},"stage":"finished","steps":[{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138850223,"name":"get :nth-child(2) > .oxd-input-group > :nth-child(2) > .oxd-input","stop":1692138850248}],"attachments":[],"parameters":[],"start":1692138849375,"name":"get :nth-child(2) > .oxd-input-group > :nth-child(2) > .oxd-input","stop":1692138850248},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138850248,"name":"uncaught exception CypressError: Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.\n\nThe command that returned the promise was:\n\n  > `cy.get()`\n\nThe cy command you invoked inside the promise was:\n\n  > `cy.get()`\n\nBecause Cypress commands are already promise-like, you don't need to wrap them or return your own promise.\n\nCypress will resolve your command with whatever the final Cypress command yields.\n\nThe reason this is an error instead of a warning is because Cypress internally queues commands serially whereas Promises execute as soon as they are invoked. Attempting to reconcile this would prevent Cypress from ever resolving.","stop":1692138850248}],"attachments":[],"parameters":[],"start":1692138849190,"name":"get function(){}","stop":1692138850250},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138850249,"name":"assert expected **<document>** to be **visible**","stop":1692138850250},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138850261,"name":"type Admin","stop":1692138850867},{"status":"passed","statusDetails":{},"stage":"finished","steps":[{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138850931,"name":"get :nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-input","stop":1692138850993}],"attachments":[],"parameters":[],"start":1692138850867,"name":"get function(){}","stop":1692138850994},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138850994,"name":"assert expected **<document>** to be **visible**","stop":1692138850994},{"status":"passed","statusDetails":{},"stage":"finished","steps":[{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138851690,"name":"get :nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-input","stop":1692138851733}],"attachments":[],"parameters":[],"start":1692138851031,"name":"type admin123","stop":1692138851733},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138851733,"name":"uncaught exception CypressError: Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.\n\nThe command that returned the promise was:\n\n  > `cy.type()`\n\nThe cy command you invoked inside the promise was:\n\n  > `cy.get()`\n\nBecause Cypress commands are already promise-like, you don't need to wrap them or return your own promise.\n\nCypress will resolve your command with whatever the final Cypress command yields.\n\nThe reason this is an error instead of a warning is because Cypress internally queues commands serially whereas Promises execute as soon as they are invoked. Attempting to reconcile this would prevent Cypress from ever resolving.","stop":1692138851733},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138851734,"name":"get .oxd-button","stop":1692138851764},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138851764,"name":"click","stop":1692138852068},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138852068,"name":"page load --waiting for new page to load--","stop":1692138852068}],"attachments":[],"parameters":[],"start":1692138849184,"name":"login (\"Admin\"; \"admin123\")","stop":1692138852068},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138852069,"name":"new url https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index","stop":1692138854411},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138854410,"name":"GET --- /web/index.php/core/i18n/messages","stop":1692138854410},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138854410,"name":"get function(){}","stop":1692138854410},{"status":"passed","statusDetails":{},"stage":"finished","steps":[{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138855522,"name":"get .oxd-topbar-header-breadcrumb > .oxd-text","stop":1692138855539}],"attachments":[],"parameters":[],"start":1692138854411,"name":"contains Dashboard","stop":1692138855541},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138855540,"name":"uncaught exception CypressError: Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.\n\nThe command that returned the promise was:\n\n  > `cy.contains()`\n\nThe cy command you invoked inside the promise was:\n\n  > `cy.get()`\n\nBecause Cypress commands are already promise-like, you don't need to wrap them or return your own promise.\n\nCypress will resolve your command with whatever the final Cypress command yields.\n\nThe reason this is an error instead of a warning is because Cypress internally queues commands serially whereas Promises execute as soon as they are invoked. Attempting to reconcile this would prevent Cypress from ever resolving.","stop":1692138855540},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138855540,"name":"GET --- /web/index.php/api/v2/dashboard/employees/action-summary","stop":1692138855540},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138855540,"name":"GET --- /web/index.php/api/v2/dashboard/shortcuts","stop":1692138855540},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138855540,"name":"GET --- /web/index.php/api/v2/buzz/feed?limit=5&offset=0&sortOrder=DESC&sortField=share.createdAtUtc","stop":1692138855540},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138855540,"name":"GET --- /web/index.php/api/v2/dashboard/employees/subunit","stop":1692138855540},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138855541,"name":"GET --- /web/index.php/api/v2/dashboard/employees/locations","stop":1692138855541},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138855541,"name":"POST --- /web/index.php/events/push","stop":1692138855541},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138855541,"name":"contains Invalid credentials","stop":1692138855551},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[{"name":"actual","value":":cy-contains(**'Invalid credentials'**), [type=**'submit'**][value~=**'Invalid credentials'**]"},{"name":"expected","value":":cy-contains('Invalid credentials'), [type='submit'][value~='Invalid credentials']"}],"start":1692138855551,"name":"assert expected **:cy-contains(**'Invalid credentials'**), [type=**'submit'**][value~=**'Invalid credentials'**]** not to exist in the DOM","stop":1692138855551},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138855551,"name":"url","stop":1692138855557},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[{"name":"actual","value":"https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index"},{"name":"expected","value":"https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index"}],"start":1692138855557,"name":"assert expected **https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index** to equal **https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index**","stop":1692138855557}],"attachments":[],"parameters":[],"labels":[{"name":"package","value":"cypress.integration.test-spec.js"},{"name":"suite","value":"Test Login Functionality"}],"links":[],"start":1692138823989,"name":"should login to the website","fullName":"should login to the website","stop":1692138855627}